### ISSUE TITLE
Display fedex api error in shopping cart page

### ISSUE THREAD

**Issue by njcyx** [scottcwilson/zencart_fedexrest#7]
FedEx server/API is down now. I tried both the legacy FedEx plug-in and REST FedEx plug-in. Neither shown a quote. 

But legacy plug-in shown the error message in the shopping cart page:

```
FedEx 
An unexpected error occurred. Please refresh this page.

FAILURE: General Failure

```
REST plug-in shown nothing, just like this plug-in was disabled.. I double checked our admin settings to make sure this plug-in was enabled.

**Comment by proseLA** [comment]
see:
https://downforeveryoneorjustme.com/fedex

**Comment by njcyx** [comment]
> see: https://downforeveryoneorjustme.com/fedex

Thanks for your link. I'm using the following service to monitor shipping api:

https://www.shippingapimonitor.com/history.html?api=fedex

It provides free email notifications.

**Comment by njcyx** [comment]
Deleted.

**Comment by proseLA** [comment]
as this is a public repo, anyone can post comments or issues.  the owner of the repo and those with write access to the repo can do as they wish.

if you want code to alert when the fedex server is down, feel free to write said code and issue a PR against this repo to see if it gets accepted.

if you are not capable of writing said code, feel free to hire someone (i'm available) to do it.

the fact that you want a feature on an open source project for a situation, and the owner has decided to not do so, seems pretty cut and dry to me.   there can be any number of reasons why he does not want to do it and has decided to close the issue.   

but just because you want it does not mean that any coder will just go ahead and do it for free.  i'm not sure why people feel that way.
